# Flutter l10n 配置文件
# 运行 flutter gen-l10n 会根据此配置自动生成 AppLocalizations 类

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated
nullable-getter: false
